### ISSUE TITLE
Doesn't play well with hypercwd

### ISSUE THREAD

**Issue by MoOx** [bevacqua/hyperterm-working-directory#2]
That would be nice to have your plugin working with this one.
- first launch: hyperterm-working-directory
- new tab: hypercwd https://www.npmjs.com/package/hypercwd

Maybe it's more a hypercwd issue, no idea yet :)

**Comment by bevacqua** [comment]
Published `0.1.1`.

- Plays well with `hypercwd`
- Supports hot configuration reloading
- Gets rid of so much code that did nothing 😅

**Comment by MoOx** [comment]
🚀👌
